Add tr() and td() functions
buggregator/trap pull request #102
Opened 2024-05-25 14:37 UTC by roxblnfk

## What was changed

Added `tr()` and `td()` shortcuts.

## Why?

## Checklist

- Closes #
- Tested
  - [ ] Tested manually
  - [ ] Unit tests added
- [ ] Documentation

2024-05-26 06:35 UTC, roxblnfk commented on src/functions.php
> +            $mem === $time and $time = microtime(true);
@lotyp looks like wrong fix

2024-05-28 08:17 UTC, roxblnfk commented on src/functions.php
> +            $mem === $time and $time = microtime(true);
It doesn't because the file in the global namespace. Sorry.

2024-05-28 12:28 UTC, lotyp requested changes

2024-05-28 12:28 UTC, lotyp commented on README.md
>  ```php
Please use `make lint-md` locally to push fixed README.md

<img width="657" alt="image" src="https://github.com/buggregator/trap/assets/94047334/7af1c7b8-4bf2-4ecf-bbc5-8effb398e820">

2024-05-28 17:38 UTC, merged